### ISSUE TITLE
Vue SFC support

### ISSUE THREAD

**Issue by atilacamurca** [Raathigesh/fabulous#10]
Support for Vue SFC (Single File Components).

A Vue SFC is a file like the following:

```vue
<template>
  <div class="d-flex">Hello</div>
</template>
<script>
export default {}
</script>
<style>
.d-flex {
  display: flex;
}
</style>
```
As we can see, there's a tag called `style` that can contain css and other pre-processors, such as scss.

The `style` tag accepts `css` code by default, or the extension specified by the `lang` attribute. Example:

```vue
<style lang="scss">
/* ... */
</style>
```

**Comment by Raathigesh** [comment]
This would be nice to have and should be fairly easy to do. If anybody wants to give it a shot, ping below and I'm more than happy to help.

**Comment by MegaMattMiller** [comment]
Started working on this in a [fork](https://github.com/MegaMattMiller/fabulous/tree/Feat_VueSfcSupport). Might not be able to fully implement it on my own.

**Comment by MegaMattMiller** [comment]
Started working on this in a [fork](https://github.com/MegaMattMiller/fabulous/tree/Feat_VueSfcSupport). Might not be able to complete it on my own.

**Comment by MegaMattMiller** [comment]
The issue I'm running into is how to break out the CSS from the SFC. Then it can be parsed like normal CSS or SCSS. I think I've [identified where that should happen](https://github.com/MegaMattMiller/fabulous/commit/927a9a16730ede84f412f3881207a07794d4b005).

**Comment by Raathigesh** [comment]
Hey @MegaMattMiller,

Thank you for trying to contribute. Appreciate your time and effort.

Below is my thought process on how we implement this:

- Since Vue file parsing is going to require some custom logic, I would create a new `vue-file` handler
- In the `vue-file` handler, we could try to get the CSS in the file by trying to find the `<style></style>` tags manually
- Then get the content between the style tags and send the pure CSS string to the [getRules ](https://github.com/Raathigesh/fabulous/blob/8ccc232408f8586fd8f17daf541352977a928b4f/src/extension/file-handlers/utils.ts#L5) function.

What do you think about the above-mentioned approach?

**Comment by MegaMattMiller** [comment]
Sounds like a plan. I'll try to work on this some this weekend.

**Comment by paustint** [comment]
@MegaMattMiller - I have opened a PR that adds support for HTML/Vue/Svelte.  Would you mind pulling the PR down and testing it to make sure it works? I am not a Vue developer, so I am not sure of all the patterns that are used aside from what I saw in the documentation.

PR: #21 

If you are able to try it out, please let me know if you have any questions or find any issues.

**Comment by MegaMattMiller** [comment]
Awesome! I've been super busy today but once I get some time I'll pull it down and test it out.
